from pynput.keyboard import Key

keymap = {
    "escape": Key.esc,
    "f1": Key.f1,
    "f2": Key.f2,
    "f3": Key.f3,
    "f4": Key.f4,
    "f5": Key.f5,
    "f6": Key.f6,
    "f7": Key.f7,
    "f8": Key.f8,
    "f9": Key.f9,
    "f10": Key.f10,
    "f11": Key.f11,
    "f12": Key.f12,
    "enter": Key.enter,
    "contextmenu": Key.menu,
    "space": Key.space,
    "enter": Key.enter,
    "win": Key.cmd,
    "ctrl": Key.ctrl_l,
    "alt": Key.alt_l,
    "shift": Key.shift,
    "insert": Key.insert,
    "delete": Key.delete,
    "backspace": Key.backspace,
    "tab": Key.tab,
    "capslock": Key.caps_lock,
    "up": Key.up,
    "down": Key.down,
    "left": Key.left,
    "right": Key.right,
    "home": Key.home,
    "end": Key.end,
    "pageup": Key.page_up,
    "pagedown": Key.page_down
}
