import difflib

keym = {
    "cutline": "ctrl+x",
    "copyline":	"ctrl+c",
    "paste": "ctrl+v",
    "deleteline": "ctrl+shift+k",
    "insertlinebelow": "ctrl+enter",
    "insertlineabove": "ctrl+shift+enter",
    "movelinedown":	"alt+down",
    "movelineup": "alt+up",
    "copylinedown": "shift+alt+down",
    "copylineup": "shift+alt+up",
    "undo":	"ctrl+z",
    "redo":	"ctrl+y",
    "addselectiontonextfindmatch": "ctrl+d",
    "movelastselectiontonextfindmatch":	"ctrl+k ctrl+d",
    "undolastcursoroperation": "ctrl+u",
    "insertcursoratendofeachlineselected": "shift+alt+i",
    "selectalloccurrencesofcurrentselection": "ctrl+shift+l",
    "selectalloccurrencesofcurrentword": "ctrl+f2",
    "selectcurrentline":"ctrl+l",
    "insertcursorbelow": "ctrl+alt+down",
    "insertcursorabove": "ctrl+alt+up",
    "jumptomatchingbracket": "ctrl+shift+\\",
    "indentline": "ctrl+]",
    "outdentline": "ctrl+[",
    "gotobeginningofline": "home",
    "gotoendofline": "end",
    "gotoendoffile": "ctrl+end",
    "gotobeginningoffile": "ctrl+home",
    "scrolllinedown": "ctrl+down",
    "scrolllineup":	"ctrl+up",
    "scrollpagedown": "alt+pagedown",
    "scrollpageup":	"alt+pageup",
    "foldregion": "ctrl+shift+[",
    "collapseregion": "ctrl+shift+[",
    "unfoldregion":	"ctrl+shift+]",
    "uncollapseregion":	"ctrl+shift+]",
    "foldallsubregions": "ctrl+k ctrl+[",
    "collapseallsubregions": "ctrl+k ctrl+[",
    "unfoldallsubregions": "ctrl+k ctrl+]",
    "uncollapseallsubregions": "ctrl+k ctrl+]",
    "foldallregions": "ctrl+k ctrl+0",
    "collapseallregions": "ctrl+k ctrl+0",
    "unfoldallregions": "ctrl+k ctrl+j",
    "uncollapseallregions": "ctrl+k ctrl+j",
    "addlinecomment": "ctrl+k ctrl+c",
    "removelinecomment": "ctrl+k ctrl+u",
    "togglelinecomment": "ctrl+/",
    "toggleblockcomment": "shift+alt+a",
    "find":	"ctrl+f",
    "replace": "ctrl+h",
    "findnext":	"enter",
    "findprevious":	"shift+enter",
    "selectalloccurrencesoffindmatch": "alt+enter",
    "togglefindcasesensitive": "alt+c",
    "togglefindregex": "alt+r",
    "togglefindwholeword": "alt+w",
    "toggleuseoftabkeyforsettingfocus":	"ctrl+m",
    "togglewordwrap": "alt+z",
    "triggersuggest": "ctrl+space",
    "triggerparameterhints": "ctrl+shift+space",
    "formatdocument": "shift+alt+f",
    "formatselection": "ctrl+k ctrl+f",
    "gotodefinition": "f12",
    "showhover": "ctrl+k ctrl+i",
    "peekdefinition": "alt+f12",
    "opendefinitiontotheside": "ctrl+k f12",
    "quickfix": "ctrl+.",
    "gotoreferences": "shift+f12",
    "renamesymbol":	"f2",
    "replacewithnextvalue":	"ctrl+shift+.",
    "replacewithpreviousvalue":	"ctrl+shift+,",
    "expandastselection": "shift+alt+right",
    "shrinkastselection": "shift+alt+left",
    "trimtrailingwhitespace": "ctrl+k ctrl+x",
    "changelanguagemode": "ctrl+k m",
    "showallsymbols": "ctrl+t",
    "gotoline":	"ctrl+g",
    "gotofile": "ctrl+p",
    "quickopen": "ctrl+p",
    "gotosymbol": "ctrl+shift+o",
    "showproblems":	"ctrl+shift+m",
    "gotonexterrororwarning": "f8",
    "gotopreviouserrororwarning": "shift+f8",
    "showallcommands": "f1",
    "navigateeditorgrouphistory": "ctrl+tab",
    "goback": "alt+left",
    "gobackinquickinput": "alt+left",
    "goforward": "alt+right",
    "newwindow": "ctrl+shift+n",
    "closewindow": "ctrl+w",
    "closeeditor": "ctrl+f4",
    "closefolder": "ctrl+k f",
    "spliteditor": "ctrl+\\",
    "focusintofirsteditorgroup": "ctrl+1",
    "focusintosecondeditorgroup": "ctrl+2",
    "focusintothirdeditorgroup": "ctrl+3",
    "moveeditorleft": "ctrl+shift+pageup",
    "moveeditorright": "ctrl+shift+pagedown",
    "moveactiveeditorgroupleft": "ctrl+k left",
    "moveactiveeditorgroupright": "ctrl+k right",
    "moveeditorintonextgroup": "ctrl+alt+right",
    "moveeditorintopreviousgroup": "ctrl+alt+left",
    "newfile": "ctrl+n",
    "openfile":	"ctrl+o",
    "save":	"ctrl+s",
    "saveall": "ctrl+k s",
    "save as": "ctrl+shift+s",
    "close": "ctrl+f4",
    "closegroup": "ctrl+k w",
    "closeall":	"ctrl+k ctrl+w",
    "reopenclosededitor": "ctrl+shift+t",
    "keepopen":	"ctrl+k enter",
    "copypathofactivefile":	"ctrl+k p",
    "revealactivefileinwindows": "ctrl+k r",
    "showopenedfileinnewwindow": "ctrl+k o",
    "togglefullscreen":	"f11",
    "togglezenmode": "ctrl+k z",
    "leavezenmode":	"escape escape",
    "zoomin": "ctrl+=",
    "zoomout": "ctrl+-",
    "togglesidebarvisibility": "ctrl+b",
    "showexplorer":	"ctrl+shift+e",
    "togglefocus":	"ctrl+shift+e",
    "showsearch": "ctrl+shift+f",
    "showsourcecontrol": "ctrl+shift+g",
    "showrun": "ctrlshift+d",
    "showextensions": "ctrl+shift+x",
    "showoutput": "ctrl+shift+u",
    "quickopenview": "ctrl+q",
    "opennewcommandprompt":	"ctrl+shift+c",
    "togglemarkdownpreview": "ctrl+shift+v",
    "openpreviewtotheside":	"ctrl+k v",
    "toggleintegratedterminal":	"ctrl+`",
    "showsearch": "ctrl+shift+f",
    "replaceinfiles": "ctrl+shift+h",
    "togglematchcase": "alt+c",
    "togglematchwholeword":	"alt+w",
    "toggleuseregularexpression": "alt+r",
    "togglesearchdetails": "ctrl+shift+j",
    "focusnextsearchresult": "f4",
    "focusprevioussearchresult": "shift+f4",
    "shownextsearchterm": "down",
    "showprevioussearchterm": "up",
    "openresultsineditor": "alt+enter",
    "focussearcheditorinput": "escape",
    "searchagain": "ctrl+shift+r",
    "deletefileresults": "ctrl+shift+backspace",
    "opensettings": "ctrl+,",
    "openkeyboardshortcuts": "ctrl+k ctrl+s",
    "selectcolortheme":	"ctrl+k ctrl+t",
    "togglebreakpoint":	"f9",
    "start": "f5",
    "continue":	"f5",
    "startwithoutdebugging": "ctrl+f5",
    "pause": "f6",
    "stepinto":	"f11",
    "runbuildtask":	"ctrl+shift+b"
}

def get_key_com(command):
    match = difflib.get_close_matches(command, list(keym.keys()))
    if len(match) > 0:
        return keym.get(match[0],'NONE')
    return 'NONE'